// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"
#include "GameplayTagsManager.h"
#include "GameplayTagContainer.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity_Unique)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity_Set)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity_Rare)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity_Magic)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Rarity_Normal)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Treasure)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Gold)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Armor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Armor_Helmet)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Armor_BodyArmor)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Weapon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Weapon_Axe)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Type_Equipment_Weapon_Sword)
